name: HomeBukkit
main: com.dinnerbone.bukkit.home.HomeBukkit
version: 0.0.3
website: http://www.bukkit.org
authors: [The Bukkit Team, jaypeetee]
database: true
description: >
             Basic home functionality.
             This plugin is a modified version of the default plugins shipped with Bukkit.
commands:
  sethome:
    aliases: [addhome,ah]
    description: Sets your current position to a home of the given name
    usage: |
           /<command> <name> [player]
           Example: /<command> BeachHouse
  listhomes:
    aliases: [homes,lh]
    description: Lists all homes that you own
    usage: /<command> [player]
  delhome:
    aliases: [deletehome,dh]
    description: Lists all homes that you own
    usage: /<command> [player]
  gohome:
    aliases: [home,gh]
    description: Goes to a home
    usage: /<command> <name> [player]